name: Build/Rest CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: ant compile jar run -f  "Source Code Inspection/nbproject"
      - name: Unit test Maven
        run: java -ea -javaagent:/snap/intellij-idea-community/387/lib/idea_rt.jar=41879:/snap/intellij-idea-community/387/bin -Dfile.encoding=UTF-8 -classpath /snap/intellij-idea-community/387/lib/idea_rt.jar:/snap/intellij-idea-community/387/plugins/junit/lib/junit5-rt.jar:/snap/intellij-idea-community/387/plugins/junit/lib/junit-rt.jar:./ticket-machine/Source Code Inspection/out/production/Source Code Inspection:./.m2/repository/junit/junit/4.13.1/junit-4.13.1.jar:./.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar com.intellij.rt.junit.JUnitStarter -ideVersion5 @w@/tmp/idea_working_dirs_junit.tmp @/tmp/idea_junit.tmp -socket38109
       
